spring:
  application:
    name: auth-service-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    root: INFO
    com.practice.authService : INFO
    org.springframework.web : INFO
    org.hibernate.sql : WARN
    org.hibernate.orm.jdbc.bind : WARN