spring:
  application:
    name: auth-service-api
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    com.practice.authService : INFO
    org.springframework.web : INFO
    org.hibernate.sql : WARN
    org.hibernate.orm.jdbc.bind : WARN